import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RootProviders from "@/components/providers/RootProviders";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Truyen Hay",
    description: "Generated by Group19 - Software Design",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body className={inter.className}>
                <RootProviders>
                    {children}
                </RootProviders>
            </body>
        </html>
    );
}
